// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc0AsPtruCioN0lleZPvJvGms7-EBtOd0',
    appId: '1:134850028826:web:20d8f9b2674cad0d4338a3',
    messagingSenderId: '134850028826',
    projectId: 'blocexample-a8c68',
    authDomain: 'blocexample-a8c68.firebaseapp.com',
    databaseURL: 'https://blocexample-a8c68-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blocexample-a8c68.firebasestorage.app',
    measurementId: 'G-BTHCC69ZT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfKAMlUf9b28j6h1LhmdqJIcHqt8IaHBU',
    appId: '1:134850028826:android:02d50ee7a660c3584338a3',
    messagingSenderId: '134850028826',
    projectId: 'blocexample-a8c68',
    databaseURL: 'https://blocexample-a8c68-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blocexample-a8c68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbk12-DL-x_F_50D-eoSjKJeFJk4n2ncE',
    appId: '1:134850028826:ios:46621828a52b1afe4338a3',
    messagingSenderId: '134850028826',
    projectId: 'blocexample-a8c68',
    databaseURL: 'https://blocexample-a8c68-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blocexample-a8c68.firebasestorage.app',
    androidClientId: '134850028826-4e6k9vmb516fo9lis9otrh0f0ja235jp.apps.googleusercontent.com',
    iosClientId: '134850028826-04ssmd6vhotr5or37f9rff57m6pvciam.apps.googleusercontent.com',
    iosBundleId: 'aiquiz.myQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbk12-DL-x_F_50D-eoSjKJeFJk4n2ncE',
    appId: '1:134850028826:ios:de6134f5d07d16b84338a3',
    messagingSenderId: '134850028826',
    projectId: 'blocexample-a8c68',
    databaseURL: 'https://blocexample-a8c68-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blocexample-a8c68.firebasestorage.app',
    androidClientId: '134850028826-4e6k9vmb516fo9lis9otrh0f0ja235jp.apps.googleusercontent.com',
    iosClientId: '134850028826-ktoj5e8k8o7o8mkacpgu5p1pub2qbskk.apps.googleusercontent.com',
    iosBundleId: 'aiquiz.myQuizApp.RunnerTests',
  );
}
